# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: AzureSpringCloud
on: push
env:
 ASC_PACKAGE_PATH: ${{ github.workspace }}
 AZURE_SUBSCRIPTION: d6b47a10-3698-4802-80a2-0a1583f65e65
jobs:
 deploy_to_production:
   runs-on: ubuntu-latest
   name: deploy to production with artifact

   steps:
   - uses: actions/checkout@v3
   - name: Set up JDK 17
     uses: actions/setup-java@v3
     with:
       java-version: '17'
       distribution: 'temurin'
       server-id: github
       settings-path: ${{ github.workspace }}

   - name: Build with Gradle
     uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
     with:
       arguments: build
   - name: Login via Azure CLI
     uses: azure/login@v1
     with:
       creds: ${{ secrets.AZURE_SECRETS }}
       
   - name: deploy to production with artifact
     uses: azure/spring-cloud-deploy@v1
     with:
       azure-subscription: ${{ env.AZURE_SUBSCRIPTION }}
       action: Deploy
       app-name: ointments_store
       use-staging-deployment: false
       package: ${{ env.ASC_PACKAGE_PATH }}/spring/build/libs/ointment-hexa-0.1.0-plain.jar
